version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:9.0.4-jdk-node-browsers

  test:
    docker:
      - image: circleci/openjdk:9.0.4-jdk-node-browsers

    steps:
      - checkout
      - run:
          name: Test
          command: |

              java org.junit.runner.JUnitCore testsrc/TestRunner

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master